language: android
android:
  components:
    - build-tools-21.1.1
    - android-17
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL_REQUEST"
    - ant debug
